version: "3.8"

services:

  # PHPとapatch
  web:
    container_name: php-apatch
    build: ./docker/php  # Dockerfileに基づいてコンテナ作成
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - .:/var/www
    depends_on:
      - mysql  # mysqlコンテナを立ち上げてから起動
    platform: linux/amd64

  # DB（mysql）
  mysql:
    container_name: mysql
    image: mysql:8.0.31  # mysql8.0.31をイメージとする
    platform: linux/amd64  # M1, M2チップに対応
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/script:/docker-entrypoint-initdb.d 
    environment:  # DBの環境変数
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Tokyo
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --innodb-use-native-aio=0

  # phpmyadmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=dbuser
      - PMA_PASSWORD=password
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    platform: linux/amd64